# 模板引擎目录
viewpath: /home/www/templates/
# MySQL数据库配置
database:
    default:
        - host:     127.0.0.1
          port:     3306
          user:     root
          pass:     123456
          name:     test
          type:     mysql
          role:     master
          charset:  utf-8
          priority: 1
        - host:     127.0.0.1
          port:     3306
          user:     root
          pass:     123456
          name:     test
          type:     mysql
          role:     master
          charset:  utf-8
          priority: 1


